/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import burgler_alarm.Config;
import events.changeSupplyReading;
import events.consolePanicBtn;
import events.deactivateSensor;
import events.detectFingerPrint;
import events.stopAlarm;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author dell
 */
public class Burgler_Alarm extends javax.swing.JFrame {

    int count = 0;

    /**
     * Creates new form NewJFrame
     */
    public Burgler_Alarm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panicBtn = new javax.swing.JButton();
        DeactivateSesorsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        room1Panel = new javax.swing.JPanel();
        windowSensorTxtField = new javax.swing.JTextField();
        DoorSensorTxtField = new javax.swing.JTextField();
        movmentTxtField = new javax.swing.JTextField();
        WindowSensorLabel = new javax.swing.JLabel();
        DoorSensorLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        room2Panel = new javax.swing.JPanel();
        WindowRoom2TxtField = new javax.swing.JTextField();
        doorSensorRoom2TxtField = new javax.swing.JTextField();
        movmentRoom2TxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DoorSnsorRoom2Label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alarmLable = new javax.swing.JLabel();
        stopAlarmBtn = new javax.swing.JButton();
        msgLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        theReadingLabel = new javax.swing.JLabel();
        powerSupplyReadingLabel = new javax.swing.JLabel();
        lessSupplyBtnBy70 = new javax.swing.JButton();
        lessSupplyBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AddFingerprintBtn = new javax.swing.JButton();
        addFingerPrintLabel = new javax.swing.JLabel();
        addFingerprint = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        panicBtn.setText("Panic");
        panicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panicBtnActionPerformed(evt);
            }
        });

        DeactivateSesorsBtn.setText("Deactivate/Activate sesors");
        DeactivateSesorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeactivateSesorsBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room 2");

        room1Panel.setBackground(new java.awt.Color(153, 153, 153));
        room1Panel.setMaximumSize(new java.awt.Dimension(3276, 3276));

        windowSensorTxtField.setText("0");

        DoorSensorTxtField.setText("0");
        DoorSensorTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoorSensorTxtFieldActionPerformed(evt);
            }
        });

        movmentTxtField.setText("0");
        movmentTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movmentTxtFieldActionPerformed(evt);
            }
        });

        WindowSensorLabel.setText("Window Sensor:");

        DoorSensorLabel.setText("Door Sensor:");

        jLabel8.setText("Movment Sensor:");

        javax.swing.GroupLayout room1PanelLayout = new javax.swing.GroupLayout(room1Panel);
        room1Panel.setLayout(room1PanelLayout);
        room1PanelLayout.setHorizontalGroup(
            room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WindowSensorLabel)
                    .addComponent(DoorSensorLabel)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoorSensorTxtField)
                    .addComponent(movmentTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windowSensorTxtField))
                .addGap(28, 28, 28))
        );
        room1PanelLayout.setVerticalGroup(
            room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room1PanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WindowSensorLabel)
                    .addComponent(windowSensorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movmentTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(44, 44, 44)
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoorSensorLabel)
                    .addComponent(DoorSensorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room 1");

        room2Panel.setBackground(new java.awt.Color(153, 153, 153));
        room2Panel.setMaximumSize(new java.awt.Dimension(3276, 3276));

        WindowRoom2TxtField.setText("0");

        doorSensorRoom2TxtField.setText("0");

        movmentRoom2TxtField.setText("0");
        movmentRoom2TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movmentRoom2TxtFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Window Sensor:");

        DoorSnsorRoom2Label.setText("Door Sensor:");

        jLabel11.setText("Movment Sensor:");

        javax.swing.GroupLayout room2PanelLayout = new javax.swing.GroupLayout(room2Panel);
        room2Panel.setLayout(room2PanelLayout);
        room2PanelLayout.setHorizontalGroup(
            room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(DoorSnsorRoom2Label)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WindowRoom2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(doorSensorRoom2TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addComponent(movmentRoom2TxtField, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(28, 28, 28))
        );
        room2PanelLayout.setVerticalGroup(
            room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room2PanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(WindowRoom2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room2PanelLayout.createSequentialGroup()
                        .addComponent(movmentRoom2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(36, 36, 36)))
                .addGroup(room2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoorSnsorRoom2Label)
                    .addComponent(doorSensorRoom2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        alarmLable.setBackground(new java.awt.Color(255, 153, 153));
        alarmLable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        alarmLable.setForeground(new java.awt.Color(255, 153, 153));
        alarmLable.setText("alarm");

        stopAlarmBtn.setText("Stop Alarm");
        stopAlarmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopAlarmBtnActionPerformed(evt);
            }
        });

        msgLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        msgLabel2.setForeground(new java.awt.Color(255, 255, 255));
        msgLabel2.setText("msg");

        ReportTable.setBackground(new java.awt.Color(204, 204, 204));
        ReportTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReportTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sensor", "Location ", "Threshold", "Intrusion time"
            }
        ));
        jScrollPane1.setViewportView(ReportTable);
        if (ReportTable.getColumnModel().getColumnCount() > 0) {
            ReportTable.getColumnModel().getColumn(0).setResizable(false);
            ReportTable.getColumnModel().getColumn(1).setResizable(false);
            ReportTable.getColumnModel().getColumn(3).setResizable(false);
        }

        theReadingLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        theReadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        theReadingLabel.setText("100");

        powerSupplyReadingLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        powerSupplyReadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        powerSupplyReadingLabel.setText("Power supply reading: ");

        lessSupplyBtnBy70.setText("Make it less by 70");
        lessSupplyBtnBy70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessSupplyBtnBy70ActionPerformed(evt);
            }
        });

        lessSupplyBtn1.setText("Make it less by 30");
        lessSupplyBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessSupplyBtn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reporting:");

        AddFingerprintBtn.setText("Add fingerprint");
        AddFingerprintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFingerprintBtnActionPerformed(evt);
            }
        });

        addFingerPrintLabel.setBackground(new java.awt.Color(255, 255, 255));
        addFingerPrintLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        addFingerPrintLabel.setForeground(new java.awt.Color(255, 255, 255));
        addFingerPrintLabel.setText("Add your finger print:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(DeactivateSesorsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panicBtn))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(stopAlarmBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alarmLable)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(room1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(room2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(powerSupplyReadingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(theReadingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lessSupplyBtn1)
                        .addGap(33, 33, 33)
                        .addComponent(lessSupplyBtnBy70)
                        .addGap(105, 105, 105))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addFingerPrintLabel)
                        .addGap(18, 18, 18)
                        .addComponent(addFingerprint)
                        .addGap(37, 37, 37)
                        .addComponent(AddFingerprintBtn)
                        .addGap(409, 409, 409))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(msgLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panicBtn)
                    .addComponent(DeactivateSesorsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopAlarmBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFingerprintBtn)
                    .addComponent(addFingerPrintLabel)
                    .addComponent(addFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(msgLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theReadingLabel)
                    .addComponent(powerSupplyReadingLabel)
                    .addComponent(lessSupplyBtnBy70)
                    .addComponent(lessSupplyBtn1))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(room2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(alarmLable)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panicBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new consolePanicBtn(true));


    }//GEN-LAST:event_panicBtnActionPerformed

    public JLabel getTheReadingLabel() {
        return theReadingLabel;
    }

    private void DeactivateSesorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeactivateSesorsBtnActionPerformed
        // TODO add your handling code here:
        count++;

        Config.sendEvent(new deactivateSensor(true, count));
    }//GEN-LAST:event_DeactivateSesorsBtnActionPerformed

    public JPanel getRoom2Panel() {
        return room2Panel;
    }

    public JPanel getRoom1Panel() {
        return room1Panel;
    }

    public JTable getReportTable() {
        return ReportTable;
    }

    private void movmentTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movmentTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movmentTxtFieldActionPerformed

    private void movmentRoom2TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movmentRoom2TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movmentRoom2TxtFieldActionPerformed

    private void DoorSensorTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoorSensorTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoorSensorTxtFieldActionPerformed

    private void stopAlarmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopAlarmBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new stopAlarm(true));
    }//GEN-LAST:event_stopAlarmBtnActionPerformed

    private void lessSupplyBtnBy70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessSupplyBtnBy70ActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new changeSupplyReading(Integer.parseInt(getTheReadingLabel().getText())-70));
    }//GEN-LAST:event_lessSupplyBtnBy70ActionPerformed

    private void lessSupplyBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessSupplyBtn1ActionPerformed
        // TODO add your handling code here:
                Config.sendEvent(new changeSupplyReading(Integer.parseInt(getTheReadingLabel().getText())-30));

    }//GEN-LAST:event_lessSupplyBtn1ActionPerformed

    public JLabel getMsgLabel2() {
        return msgLabel2;
    }

    private void AddFingerprintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFingerprintBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new detectFingerPrint(getAddFingerprint().getText()));
    }//GEN-LAST:event_AddFingerprintBtnActionPerformed

    public JTextField getAddFingerprint() {
        return addFingerprint;
    }

    public JButton getAddFingerprintBtn() {
        return AddFingerprintBtn;
    }

    public JLabel getAddFingerPrintLabel() {
        return addFingerPrintLabel;
    }

    public JLabel getAlarmLable() {
        return alarmLable;
    }

    /**
     * @param args the command line arguments
     */
    public JButton getPanicBtn() {
        return panicBtn;
    }

    public JLabel getMsgLabel() {
        return msgLabel2;
    }

    public JTextField getMovmentTxtField() {
        return movmentTxtField;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFingerprintBtn;
    private javax.swing.JButton DeactivateSesorsBtn;
    private javax.swing.JLabel DoorSensorLabel;
    private javax.swing.JTextField DoorSensorTxtField;
    private javax.swing.JLabel DoorSnsorRoom2Label;
    private javax.swing.JTable ReportTable;
    private javax.swing.JTextField WindowRoom2TxtField;
    private javax.swing.JLabel WindowSensorLabel;
    private javax.swing.JLabel addFingerPrintLabel;
    private javax.swing.JTextField addFingerprint;
    private javax.swing.JLabel alarmLable;
    private javax.swing.JTextField doorSensorRoom2TxtField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lessSupplyBtn1;
    private javax.swing.JButton lessSupplyBtnBy70;
    private javax.swing.JTextField movmentRoom2TxtField;
    private javax.swing.JTextField movmentTxtField;
    private javax.swing.JLabel msgLabel2;
    private javax.swing.JButton panicBtn;
    private javax.swing.JLabel powerSupplyReadingLabel;
    private javax.swing.JPanel room1Panel;
    private javax.swing.JPanel room2Panel;
    private javax.swing.JButton stopAlarmBtn;
    private javax.swing.JLabel theReadingLabel;
    private javax.swing.JTextField windowSensorTxtField;
    // End of variables declaration//GEN-END:variables

    public JLabel getDoorSensorLabel() {
        return DoorSensorLabel;
    }

    public JTextField getDoorSensorTxtField() {
        return DoorSensorTxtField;
    }

    public JLabel getWindowSensorLabel() {
        return WindowSensorLabel;
    }

    public JTextField getMovmentRoom2TxtField() {
        return movmentRoom2TxtField;
    }

    public JLabel getDoorSnsorRoom2Label() {
        return DoorSnsorRoom2Label;
    }

    public JTextField getWindowRoom2TxtField() {
        return WindowRoom2TxtField;
    }

    public JTextField getDoorSensorRoom2TxtField() {
        return doorSensorRoom2TxtField;
    }

    public JTextField getWindowSensorTxtField() {
        return windowSensorTxtField;
    }
}
